list tasks
jjauzion/ws-backend pull request #16
Opened 2021-02-28 18:57 UTC by benka-me

close #5

2021-02-28 19:39 UTC, jjauzion reviewed
bon du coup si on change le package client ES faut le changer partout parce que 2 client c'est hard ^^

2021-02-28 19:39 UTC, jjauzion commented on db/es_task.go
> +			es.log.Warn("json failed", zap.Error(err))
log.Error non ? Ca fait planter l'execution si ya une erreur donc c'est pas un warning

2021-02-28 19:39 UTC, jjauzion commented on graph/schema.graphqls
>    id: ID!
on peut aussi supprimer l'id alors, en gros si on enleve le created_by => une task = un job donc pas besoin d'id pour le job

2021-02-28 19:39 UTC, jjauzion commented on graph/schema.resolvers.go
> +	graph "github.com/jjauzion/ws-backend/graph/model"
je comprends pas ce changement, maintenant on a deux `model/`, un a la racine du projet et un dans `graph/` ... ??

2021-02-28 19:39 UTC, jjauzion commented on graph/schema.resolvers.go
> +	return graph.UserFromModel(newUser).Ptr(), nil
? pourquoi tu utilise UserFromModel? c'est quoi ce machin

2021-02-28 20:34 UTC, benka-me commented on graph/schema.resolvers.go
> +	return graph.UserFromModel(newUser).Ptr(), nil
il convertit le db model vers le model graph 🤪 Le naming est pas fou j'en convient

2021-02-28 20:35 UTC, benka-me commented on graph/schema.resolvers.go
> +	graph "github.com/jjauzion/ws-backend/graph/model"
Il y a le model backend (ou db) et le model graphql

2021-02-28 20:37 UTC, benka-me commented on graph/schema.graphqls
>    id: ID!
oui c'était aussi ce que je pensais mais je pensais qu'il y avait une raison à créer un job (peut-etre plusieurs job)

2021-02-28 20:37 UTC, benka-me commented on db/es_task.go
> +			es.log.Warn("json failed", zap.Error(err))
Yes!

2021-02-28 20:37 UTC, benka-me commented
> bon du coup si on change le package client ES faut le changer partout parce que 2 client c'est hard ^^

@jjauzion new issue?

2021-03-01 10:47 UTC, jjauzion commented on graph/schema.resolvers.go
> +	return graph.UserFromModel(newUser).Ptr(), nil
ooh je vois, je croyais que c'etait un truc généré par graphQL, je regard ça ce midi

2021-03-01 19:58 UTC, jjauzion commented
- naming: eg: FromUserDBModel
- move `model/` in `db/`
- move graphql model in `graph/`

2021-03-07 15:23 UTC, jjauzion requested changes
rename task.go to task_logger.go

2021-03-07 15:23 UTC, jjauzion commented on db/es_task.go
> +			es.log.Warn("json failed", zap.Error(err))
```suggestion
			es.log.Error("json failed", zap.Error(err))
```

2021-03-07 15:23 UTC, jjauzion commented on db/es_task_test.go
> +	wait := time.Millisecond * 1100
plutot que de faire un wait, quand on crée des données dans Elastic on peut lui dire d'attendre que la donnée soit écrite et répliqué sur tous les noeuds avant de retourner. mais bon on fera plus tard

2021-03-07 15:38 UTC, jjauzion approved these changes
LQTM !

2021-03-07 15:38 UTC, merged