Benka/feat/one elastic client
jjauzion/ws-backend pull request #23
Opened 2021-03-07 19:58 UTC by benka-me

- [ ]  close #19 
- [ ]  close #20
- [ ]  close #3

2021-03-20 17:11 UTC, jjauzion requested changes

2021-03-20 17:11 UTC, jjauzion commented on db/es_user.go
> +	_, err = es.GetUserByEmail(ctx, user.Email)
je trouve bizarre d'avoir en retour d'une fct de search une erreur si on a aucun match. On devrait avoir une erreur si le search fail, mais aucun match c'est un resultat valide, pas une erreur, il faudrait plutot check le `len()` du resultat

2021-03-20 17:11 UTC, jjauzion commented on db/es_user.go
> +	_, err = es.GetUserByEmail(ctx, user.Email)
j'ai créé une issue pour ça (pas forcement a traiter dans cet PR)

2021-03-20 17:50 UTC, jjauzion commented
et ya aussi le bootstrap qui marche plus pour gql, je viens de voir ça

il faut pas faire:
```
if bootstrap {
		if err := dbal.Bootstrap(ctx); err != nil {
			resolver.Log.Error("bootstrap failed", zap.Error(err))
			return
		}
	}
```

il faut faire:
```
if bootstrap {
		if err := db.Bootstrap(ctx, dbal); err != nil {
			lg.Error("bootstrap failed", zap.Error(err))
			return
		}
	}
```

c'est exactement pour ça que je le trouvait pas clair ce bootstrap '^^ renomer en dbal c'est pas suffisant, on peut aussi renomer le `dbal.Bootstrap` en `dbal.Initialize`

2021-03-21 13:59 UTC, benka-me commented on db/es.go
>  }
Elle n'est utilisé nul part 🥲

2021-03-21 14:26 UTC, benka-me commented on db/es.go
> +	return nil, fmt.Errorf("something wrong happened")
Il est déjà dessus non?

2021-03-21 14:32 UTC, benka-me commented on db/es.go
> +func (es *esHandler) getMapping(file string) string {
"Avoid meaningless package names like util, common, misc, api"

https://github.com/golang/go/wiki/CodeReviewComments#package-names

2021-03-21 17:45 UTC, jjauzion commented on db/error.go
> +	ErrTooManyRows = fmt.Errorf("found too many hits")
```suggestion
	ErrTooManyHits = fmt.Errorf("found too many hits")
```

2021-03-21 17:45 UTC, jjauzion commented on db/es.go
>  	elastic *elastic.Client
on devrait peut etre le renommer en client maintenant que l'autre client est supprimé ?

2021-03-21 17:45 UTC, jjauzion commented on db/es.go
> +	es.log.Info("successfully connected to ES")
ce message il le faudrait plutot apres le ping non ?

2021-03-21 17:45 UTC, jjauzion commented on db/es.go
> +func (es *esHandler) readMappingFile(file string) string {
on change pas celle la du coup ?

2021-03-21 17:52 UTC, benka-me commented on db/error.go
> +	ErrTooManyRows = fmt.Errorf("found too many hits")
Tain...

2021-03-21 17:52 UTC, benka-me commented on db/es.go
> +func (es *esHandler) readMappingFile(file string) string {
Que veux-tu dire?

2021-03-21 18:05 UTC, jjauzion approved these changes
!!

2021-03-21 18:06 UTC, merged