Jj/feature/docker env
jjauzion/ws-backend pull request #46
Opened 2021-04-03 13:57 UTC by jjauzion

close #43

2021-04-04 17:27 UTC, benka-me requested changes

2021-04-04 17:27 UTC, benka-me commented on README.md
> +  create_task(input:{user_id:"65941391-733a-430c-a3bd-2bdd853af7be", docker_image:"jjauzion/ws-mock-container", dataset:"s3//"}) {
Ici il n'y a plus de userID car il est dans le token

2021-04-04 17:27 UTC, benka-me commented on README.md
> +  create_task(input:{env:"WANDB_API_KEY=putYourKeyHere", docker_image:"jjauzion/wandb-test", dataset:"s3//"}) {
Ici je ne comprends pas pourquoi on doit nommé la variable et pas simplement passer la clé API.

2021-04-04 17:27 UTC, benka-me commented on graph/schema.graphqls
> +  env: [String!]
Pas plutôt `[String]!` ?

2021-04-04 17:27 UTC, benka-me commented on graph/schema.graphqls
> +  env: [String!]
Et puis si une env contient le Nom et le contenu pourquoi ne pas utiliser une map?

2021-04-04 17:27 UTC, benka-me commented on proto/api.proto
> +  repeated string env = 3;
Idem on peut passer une map non?

2021-04-05 08:44 UTC, jjauzion commented on README.md
> +  create_task(input:{user_id:"65941391-733a-430c-a3bd-2bdd853af7be", docker_image:"jjauzion/ws-mock-container", dataset:"s3//"}) {
bien vu je me suis emmelé les pinceaux dans des copier coller de readme

2021-04-05 08:52 UTC, jjauzion commented on README.md
> +  create_task(input:{env:"WANDB_API_KEY=putYourKeyHere", docker_image:"jjauzion/wandb-test", dataset:"s3//"}) {
Ca donne plus de flexibilité si le user veut passer d'autre variable d'env ou si quelqu'un veut utiliser autre chose que wandb. Sinon il faut marquer en dur le nom de la var env dans notre code

2021-04-05 08:55 UTC, jjauzion commented on graph/schema.graphqls
> +  env: [String!]
au début j'avais mis une map mais docker prend une list de string donc j'ai préférer garder leur format. Et `[String!]` parce qu'on est pas obligé de passer des var env, par contre je veux pas une liste avec du `null` dedans

2021-04-05 09:03 UTC, jjauzion commented on proto/api.proto
> +  repeated string env = 3;
idem j'ai gardé le mm format partout pour etre cohérent

2021-04-05 12:55 UTC, benka-me approved these changes
Ok désolé pour le commentaire inutile

2021-04-05 16:53 UTC, merged